### PR TITLE
add basic help on fail; tiny cleanup

### PR DESCRIPTION
**Pull request by ianare**
Added basic usage of the program when an error is detected: bad argument or missing file.
This could be extended further to have a "real" help output from the program.

Added a gitignore file.

Also a tiny bit of cleanup on some files.

### CODE REVIEW

**Comment by mandovinnie** [comment]
Hi Ianare -

 I included your usage block in the main branch of code and increased the
block size in dvi_print.cc.   I find much of the clean up a distraction as
I have to look through all the changes to see which are just formatting.
Does your development environment complain about trailing whitespaces and
insist on protections against reading a .h file more than once?

 Wayne

**Comment by ianare** [comment]
Hi Wayne,

Thanks for adding my contributions :-)

I can see how this could be annoying for you to mix a new feature and cleanup on same PR. I'll not do that in the future.

I'm using Kdevelop 4 on KDE Neon, and yes I'm getting warnings about double inclusion, which makes editing annoying since the pop-up keeps appearing. I would say it's also good practice.

For the line endings and mix of tabs and spaces, this creates incoherent display and makes it harder for me to reason about the code. Again, for me this would fall in the "good practice" category.

It might be useful to define somewhere a style guide for use in the project (a `CONTRIBUTING.md` file is the standard on Github). The main incoherence I've seen is with indentation (tabs, 4 spaces, 2 spaces).

As an example of a modern style guide: https://google.github.io/styleguide/cppguide.html

I also think the .gitignore file is important, since it makes it impossible to accidentally commit generated files (like *.o). This makes it easier for other people to join the project. I can do a single PR for this you want.

Thank you,

- ianaré

**Comment by mandovinnie** [comment]
Hello Ianaré -

 I will look at Kdevelop.  I use emacs and gcc so I am using good practice from 1999.  Emacs does put in extra spaces.  The standard indentation has changed over the years, as it used to indent more.  Would the #pragma once work for you for the include files?

 You are the first person to do a git pull ever.  Most people in the past have just sent me suggestions or bits of code.  I don’t actually use github for my development - I make tarballs and then use them to update github.  Again, a very old way of doing things.  If I had a working .gitignore it would be very long as I have 660 files in my development directory.

 Wayne

**Comment by ianare** [comment]
> Hello Ianaré - I will look at Kdevelop. I use emacs and gcc so I am using good practice from 1999. Emacs does put in extra spaces. The standard indentation has changed over the years, as it used to indent more.

Not sure it would be better than emacs for one used to it. Maybe just using a .editorconfig file would do the trick for the indents and spaces, there's a plugin for emacs.

https://editorconfig.org/

> Would the #pragma once work for you for the include files?

Yes, absolutely. I had actually done that first, but the ifdef style is maybe more universal, so I had changed the PR. But yeah #pragma once is the way forward.

> You are the first person to do a git pull ever. Most people in the past have just sent me suggestions or bits of code. I don’t actually use github for my development - I make tarballs and then use them to update github. Again, a very old way of doing things.

Nothing wrong with that. Git is nice too once you get used to it. I've worked on some open source projects, having a good code organization and documentation helps a lot for new comers. Although I admit the intersection of "can read 16th century lute tablature" and "knows C++" must not be that common ;-)

>  If I had a working .gitignore it would be very long as I have 660 files in my development directory. 

It doesn't have to cover all cases to be useful. In fact the file I proposed is rather minimal, but covers all files that I generated during compilation, temp files, etc.

You can use glob patterns in the .gitignore to filter out files.

Best,

ianaré

**Pull request closed without merging**
